services:
  palmr:
    image: kyantech/palmr:latest
    container_name: palmr
    environment:
      - ENABLE_S3=false
      - ENCRYPTION_KEY=change-this-key-in-production-min-32-chars # CHANGE THIS KEY FOR SECURITY
    ports:
      - "5487:5487" # Web port
      - "3333:3333" # API port (OPTIONAL EXPOSED - ONLY IF YOU WANT TO ACCESS THE API DIRECTLY)
    volumes:
      - ./palmr_data:/app/server/uploads # Volume for storing uploads
      - ./palmr_db:/app/server/db #Volume for storing the palmr database
      - ./palmr_temp:/app/server/temp-chunks # OPTIONAL Volume for storing temporary chunks
    restart: unless-stopped # Restart the container unless it is stopped

