/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["bootstrap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/branding/{asset}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["public_branding"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_sessions"];
        put?: never;
        post?: never;
        delete: operations["revoke_sessions"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revoke_session"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/effective": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["effective_settings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["complete_setup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["setup_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/docs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["docs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/docs/scalar.js": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["scalar_runtime"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["live"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manifest.webmanifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["manifest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["openapi_document"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiErrorBody: {
            error: components["schemas"]["ApiErrorPayload"];
        };
        ApiErrorPayload: {
            /** @description Stable machine-readable code; the only field clients branch on. */
            code: components["schemas"]["ErrorCode"];
            /** @description Code-specific machine-readable fields; always an object, possibly empty. */
            details: {
                [key: string]: components["schemas"]["DetailValue"];
            };
            /** @description English text for logs and operators; never displayed or compared. */
            message: string;
            /** @description Equals the `X-Request-Id` response header. */
            requestId: string;
        };
        Bootstrap: {
            appDescription: string;
            appName: string;
            defaultLocale: string;
            faviconUrl: string | null;
            logoUrl: string | null;
            passwordLoginEnabled: boolean;
            poweredByVisible: boolean;
            primaryColor: string;
            providers: components["schemas"]["BootstrapProvider"][];
            setupCompleted: boolean;
            supportedLocales: string[];
            version: string | null;
        };
        BootstrapProvider: {
            displayName: string;
            iconKey: string;
            slug: string;
            /** Format: int64 */
            sortOrder: number;
        };
        /** @enum {string} */
        DatabaseHealthStatus: "ok";
        DetailValue: boolean | number | string | string[];
        EffectiveSettings: {
            aliasPattern: string;
            /** Format: int32 */
            maxConcurrentTransfers: number;
            /** Format: int64 */
            maxFileSizeBytes: number | null;
            /** Format: int32 */
            maxPublicLinkLifetimeDays: number | null;
            /** Format: int32 */
            passwordMinLength: number;
            /** Format: int32 */
            publicLinkPasswordMinLength: number;
            /** Format: int64 */
            quotaBytes: number | null;
            /** Format: int32 */
            receivedRetentionMaxDays: number | null;
            smtpConfigured: boolean;
            /** @example local */
            storageProvider: string;
            /** Format: int32 */
            trustedDeviceDurationDays: number;
            trustedDevicesEnabled: boolean;
            twoFactorRequired: boolean;
        };
        /** @enum {string} */
        ErrorCode: "VALIDATION_ERROR" | "INVALID_JSON" | "NOT_FOUND" | "METHOD_NOT_ALLOWED" | "FORBIDDEN" | "UNSUPPORTED_MEDIA_TYPE" | "REQUEST_BODY_TOO_LARGE" | "REQUEST_TIMEOUT" | "INTERNAL_ERROR" | "SERVICE_UNAVAILABLE" | "CURSOR_INVALID" | "RATE_LIMITED" | "CSRF_TOKEN_MISSING" | "CSRF_TOKEN_INVALID" | "ORIGIN_NOT_ALLOWED" | "IDEMPOTENCY_KEY_CONFLICT" | "IDEMPOTENCY_REQUEST_IN_PROGRESS" | "BATCH_TOO_LARGE" | "FEATURE_UNAVAILABLE_SMTP" | "SETUP_ALREADY_COMPLETED" | "AUTH_REQUIRED" | "AUTH_INVALID_CREDENTIALS" | "AUTH_LOCKED" | "AUTH_PASSWORD_LOGIN_DISABLED" | "AUTH_RECENT_AUTH_REQUIRED" | "AUTH_PASSWORD_CHANGE_REQUIRED" | "AUTH_2FA_ENROLLMENT_REQUIRED" | "SESSION_NOT_FOUND" | "PASSWORD_POLICY_VIOLATION" | "USER_EMAIL_TAKEN" | "USER_USERNAME_TAKEN" | "DATABASE_BUSY" | "FILE_NOT_FOUND" | "RANGE_NOT_SATISFIABLE" | "STORAGE_UNAVAILABLE" | "STORAGE_FULL" | "STORAGE_PROVIDER_MISMATCH" | "STORAGE_SIZE_MISMATCH" | "BRANDING_ASSET_UNKNOWN";
        HealthLive: {
            status: components["schemas"]["HealthLiveStatus"];
            version: string;
        };
        /** @enum {string} */
        HealthLiveStatus: "ok";
        HealthNotReady: {
            reason?: null | components["schemas"]["HealthReason"];
            status: components["schemas"]["HealthNotReadyStatus"];
            version: string;
        };
        /** @enum {string} */
        HealthNotReadyStatus: "not_ready";
        HealthReady: {
            database?: null | components["schemas"]["DatabaseHealthStatus"];
            migrations?: null | components["schemas"]["MigrationHealthStatus"];
            status: components["schemas"]["HealthReadyStatus"];
            storage?: null | components["schemas"]["StorageHealthStatus"];
            version: string;
        };
        /** @enum {string} */
        HealthReadyStatus: "ready";
        /** @enum {string} */
        HealthReason: "storage_down" | "storage_unreachable" | "database_not_writable" | "database_unavailable" | "migrations_pending";
        HealthSummary: {
            database?: null | components["schemas"]["DatabaseHealthStatus"];
            live: boolean;
            ready: boolean;
            reason?: null | components["schemas"]["HealthReason"];
            status: components["schemas"]["HealthSummaryStatus"];
            storage?: null | components["schemas"]["StorageHealthStatus"];
            version: string;
        };
        /** @enum {string} */
        HealthSummaryStatus: "ok" | "degraded" | "not_ready";
        LoginRequest: {
            /** @example ada@example.com */
            identifier: string;
            /** Format: password */
            password: string;
        };
        LoginResponse: {
            mfaEnrollmentRequired: boolean;
            mustChangePassword: boolean;
            user: components["schemas"]["LoginUser"];
        };
        LoginUser: {
            /** @example /api/v1/profile/avatar */
            avatarUrl: string | null;
            email: string;
            firstName: string;
            id: string;
            isActive: boolean;
            lastName: string;
            /** @example en-US */
            locale: string;
            /** @example admin */
            role: string;
            username: string;
        };
        ManifestIcon: {
            sizes: string;
            src: string;
            type: string;
        };
        MeCapabilities: {
            canChangePassword: boolean;
            hasLocalPassword: boolean;
            /** Format: int32 */
            identityLinkCount: number;
            twoFactorEnabled: boolean;
        };
        MeResponse: {
            capabilities: components["schemas"]["MeCapabilities"];
            restriction: null | components["schemas"]["RestrictionName"];
            session: components["schemas"]["MeSession"];
            user: components["schemas"]["MeUser"];
        };
        MeSession: {
            createdAt: string;
            expiresAt: string;
            id: string;
            lastSeenAt: string;
            recentAuthUntil: string;
        };
        MeUser: {
            /** @example blue */
            accent: string;
            /** @example /api/v1/profile/avatar */
            avatarUrl: string | null;
            createdAt: string;
            email: string;
            firstName: string;
            id: string;
            isActive: boolean;
            lastName: string;
            /** @example pt-BR */
            locale: string;
            pendingEmail: string | null;
            /** @example admin */
            role: string;
            /** @example system */
            theme: string;
            username: string;
        };
        /** @enum {string} */
        MigrationHealthStatus: "current";
        Page_SessionItem: {
            items: {
                absoluteExpiresAt: string;
                createdAt: string;
                expiresAt: string;
                id: string;
                ipAddress: string | null;
                isCurrent: boolean;
                lastSeenAt: string;
                origin: components["schemas"]["SessionOrigin"];
                userAgent: string | null;
            }[];
            /** @description Opaque cursor for the next page; `null` on the last page. */
            nextCursor: string | null;
            /**
             * Format: int64
             * @description Matching items overall; `null` where counting would require a scan.
             */
            totalCount: number | null;
        };
        /** @enum {string} */
        RestrictionName: "must_change_password" | "mfa_enrollment_required";
        SessionItem: {
            absoluteExpiresAt: string;
            createdAt: string;
            expiresAt: string;
            id: string;
            ipAddress: string | null;
            isCurrent: boolean;
            lastSeenAt: string;
            origin: components["schemas"]["SessionOrigin"];
            userAgent: string | null;
        };
        /** @enum {string} */
        SessionOrigin: "password" | "external";
        SetupRequest: {
            /** @example Palmr */
            appName: string;
            email: string;
            firstName: string;
            lastName: string;
            /** @example en-US */
            locale: string;
            /** Format: password */
            password: string;
            username: string;
        };
        SetupResponse: {
            mustChangePassword: boolean;
            user: components["schemas"]["SetupUser"];
        };
        SetupStatus: {
            /** Format: int32 */
            passwordMinLength?: number;
            setupCompleted: boolean;
        };
        SetupUser: {
            email: string;
            id: string;
            isActive: boolean;
            /** @example admin */
            role: string;
            username: string;
        };
        /** @enum {string} */
        StorageHealthStatus: "ok" | "degraded" | "down";
        WebAppManifest: {
            background_color: string;
            icons: components["schemas"]["ManifestIcon"][];
            name: string;
            short_name: string;
            theme_color: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Signed in; `palmr_session` and `palmr_csrf` are set and any presented session is revoked. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description The body is not parseable JSON. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description The credentials did not authenticate. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Password login is disabled, or the origin is not allowed. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description The request is not JSON. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description The request failed validation. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Rate limited, or the account is locked after the password was proven. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current session is revoked, or none remained; `palmr_session` and `palmr_csrf` are cleared. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A presented session lacks its CSRF proof, or the origin is not allowed. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's current authentication state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Authentication required. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
        };
    };
    bootstrap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The instance description the SPA needs before it knows the visitor. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bootstrap"];
                };
            };
        };
    };
    public_branding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description logo | favicon | login-background | og-image | email-logo */
                asset: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The effective branding asset bytes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": number[];
                    "image/webp": number[];
                };
            };
            /** @description The cached asset is still current. */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown or disabled asset. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
        };
    };
    list_sessions: {
        parameters: {
            query?: {
                /** @description Opaque pagination cursor. */
                cursor?: string;
                /** @description Page size. */
                limit?: number;
                /** @description Sort: lastSeenAt:asc|desc */
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's active sessions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_SessionItem"];
                };
            };
            /** @description Invalid cursor or query. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Authentication required. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
        };
    };
    revoke_sessions: {
        parameters: {
            query?: {
                /** @description Also revoke the current session. */
                includeCurrent?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessions revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authentication required. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Recent authentication required. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Invalid query. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
        };
    };
    revoke_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session UUIDv7 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authentication required. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Unknown or foreign session. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
        };
    };
    effective_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The read-only policy slice the SPA must respect for the caller. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EffectiveSettings"];
                };
            };
            /** @description Authentication required. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
        };
    };
    complete_setup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupRequest"];
            };
        };
        responses: {
            /** @description The first Admin was created and signed in; `palmr_session` and `palmr_csrf` are set. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupResponse"];
                };
            };
            /** @description The body is not parseable JSON. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Setup is already complete, or the identity is taken. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description The request is not JSON. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description The request failed validation or the password policy. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
        };
    };
    setup_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Whether first-run setup is complete, and the account password policy while it is not. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatus"];
                };
            };
        };
    };
    docs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Scalar API reference for this instance. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": unknown;
                };
            };
            /** @description The page could not be rendered. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
        };
    };
    scalar_runtime: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Scalar API reference runtime served by this instance. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/javascript": unknown;
                };
            };
            /** @description The cached runtime is still current. */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    summary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The instance is ready. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthSummary"];
                };
            };
            /** @description The instance is not ready. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthSummary"];
                };
            };
        };
    };
    live: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process is responsive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthLive"];
                };
            };
        };
    };
    ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Traffic may be routed to this instance. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthReady"];
                };
            };
            /** @description Traffic must not be routed to this instance. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthNotReady"];
                };
            };
        };
    };
    manifest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The instance-branded web app manifest. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/manifest+json": components["schemas"]["WebAppManifest"];
                };
            };
            /** @description The cached manifest is still current. */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    openapi_document: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The OpenAPI 3.1 description of this instance's HTTP API. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description The cached document is still current. */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
