/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/docs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["docs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/docs/scalar.js": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["scalar_runtime"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["live"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manifest.webmanifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["manifest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["openapi_document"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiErrorBody: {
            error: components["schemas"]["ApiErrorPayload"];
        };
        ApiErrorPayload: {
            /** @description Stable machine-readable code; the only field clients branch on. */
            code: components["schemas"]["ErrorCode"];
            /** @description Code-specific machine-readable fields; always an object, possibly empty. */
            details: {
                [key: string]: components["schemas"]["DetailValue"];
            };
            /** @description English text for logs and operators; never displayed or compared. */
            message: string;
            /** @description Equals the `X-Request-Id` response header. */
            requestId: string;
        };
        /** @enum {string} */
        DatabaseHealthStatus: "ok";
        DetailValue: boolean | number | string;
        /** @enum {string} */
        ErrorCode: "VALIDATION_ERROR" | "NOT_FOUND" | "METHOD_NOT_ALLOWED" | "FORBIDDEN" | "UNSUPPORTED_MEDIA_TYPE" | "REQUEST_BODY_TOO_LARGE" | "REQUEST_TIMEOUT" | "INTERNAL_ERROR" | "SERVICE_UNAVAILABLE" | "CURSOR_INVALID" | "RATE_LIMITED" | "CSRF_TOKEN_MISSING" | "CSRF_TOKEN_INVALID" | "ORIGIN_NOT_ALLOWED" | "IDEMPOTENCY_KEY_CONFLICT" | "IDEMPOTENCY_REQUEST_IN_PROGRESS" | "BATCH_TOO_LARGE" | "FEATURE_UNAVAILABLE_SMTP" | "SETUP_ALREADY_COMPLETED" | "DATABASE_BUSY" | "FILE_NOT_FOUND" | "RANGE_NOT_SATISFIABLE" | "STORAGE_UNAVAILABLE" | "STORAGE_FULL" | "STORAGE_PROVIDER_MISMATCH";
        HealthLive: {
            status: components["schemas"]["HealthLiveStatus"];
            version: string;
        };
        /** @enum {string} */
        HealthLiveStatus: "ok";
        HealthNotReady: {
            reason?: null | components["schemas"]["HealthReason"];
            status: components["schemas"]["HealthNotReadyStatus"];
            version: string;
        };
        /** @enum {string} */
        HealthNotReadyStatus: "not_ready";
        HealthReady: {
            database?: null | components["schemas"]["DatabaseHealthStatus"];
            migrations?: null | components["schemas"]["MigrationHealthStatus"];
            status: components["schemas"]["HealthReadyStatus"];
            storage?: null | components["schemas"]["StorageHealthStatus"];
            version: string;
        };
        /** @enum {string} */
        HealthReadyStatus: "ready";
        /** @enum {string} */
        HealthReason: "storage_down" | "storage_unreachable" | "database_not_writable" | "database_unavailable" | "migrations_pending";
        HealthSummary: {
            database?: null | components["schemas"]["DatabaseHealthStatus"];
            live: boolean;
            ready: boolean;
            reason?: null | components["schemas"]["HealthReason"];
            status: components["schemas"]["HealthSummaryStatus"];
            storage?: null | components["schemas"]["StorageHealthStatus"];
            version: string;
        };
        /** @enum {string} */
        HealthSummaryStatus: "ok" | "degraded" | "not_ready";
        ManifestIcon: {
            sizes: string;
            src: string;
            type: string;
        };
        /** @enum {string} */
        MigrationHealthStatus: "current";
        /** @enum {string} */
        StorageHealthStatus: "ok" | "degraded" | "down";
        WebAppManifest: {
            background_color: string;
            icons: components["schemas"]["ManifestIcon"][];
            name: string;
            short_name: string;
            theme_color: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    docs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Scalar API reference for this instance. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": unknown;
                };
            };
            /** @description The page could not be rendered. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
        };
    };
    scalar_runtime: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Scalar API reference runtime served by this instance. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/javascript": unknown;
                };
            };
            /** @description The cached runtime is still current. */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    summary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The instance is ready. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthSummary"];
                };
            };
            /** @description The instance is not ready. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthSummary"];
                };
            };
        };
    };
    live: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process is responsive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthLive"];
                };
            };
        };
    };
    ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Traffic may be routed to this instance. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthReady"];
                };
            };
            /** @description Traffic must not be routed to this instance. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthNotReady"];
                };
            };
        };
    };
    manifest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The instance-branded web app manifest. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/manifest+json": components["schemas"]["WebAppManifest"];
                };
            };
            /** @description The cached manifest is still current. */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    openapi_document: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The OpenAPI 3.1 description of this instance's HTTP API. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description The cached document is still current. */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
