use anyhow::{ensure, Result};
use palmr_stress::gen::{
    generate_bytes, GenError, GeneratedStream, Seed, BLOCK_SIZE, MAX_STREAM_SIZE, STREAM_CHUNK_SIZE,
};
use palmr_stress::vectors::ReferenceVectors;

const KIB: u64 = 1024;
const MIB: u64 = 1024 * KIB;
const GIB: u64 = 1024 * MIB;

fn seed(last: u8) -> Seed {
    let mut bytes = [0u8; 32];
    bytes[31] = last;
    Seed::from_bytes(bytes)
}

fn read_all(seed: &Seed, size: u64, chunk: usize) -> Result<Vec<u8>> {
    let mut stream = GeneratedStream::new(seed, size)?;
    let mut out = Vec::new();
    let mut buf = vec![0u8; chunk];
    loop {
        let n = stream.read(&mut buf)?;
        if n == 0 {
            return Ok(out);
        }
        out.extend_from_slice(&buf[..n]);
    }
}

#[test]
fn unit_gen_seek_is_o1() -> Result<()> {
    let vectors = ReferenceVectors::load_default().map_err(anyhow::Error::msg)?;
    let expected = vectors
        .slices
        .iter()
        .find(|v| v.seed == seed(1) && v.offset == 16 * GIB)
        .ok_or_else(|| anyhow::anyhow!("no 16 GiB vector"))?;

    let mut stream = GeneratedStream::new(&seed(1), MAX_STREAM_SIZE)?;
    ensure!(stream.cipher_position()? == 0 && stream.generated_bytes() == 0);

    stream.seek(16 * GIB)?;
    ensure!(stream.position() == 16 * GIB);
    ensure!(
        stream.cipher_position()? == 16 * GIB,
        "the cipher counter must jump directly to the requested offset"
    );
    ensure!(
        stream.generated_bytes() == 0,
        "seeking must not generate any keystream"
    );

    let mut out = vec![0u8; expected.bytes.len()];
    ensure!(stream.read(&mut out)? == out.len());
    ensure!(
        out == expected.bytes,
        "bytes at 16 GiB differ from the reference"
    );
    ensure!(stream.generated_bytes() == out.len() as u64);
    ensure!(stream.cipher_position()? == 16 * GIB + out.len() as u64);
    Ok(())
}

#[test]
fn unit_gen_seek_work_depends_on_length_not_offset() -> Result<()> {
    for offset in [
        0,
        1,
        31,
        63,
        64,
        65,
        127,
        128,
        129,
        4095,
        4096,
        4097,
        MIB,
        64 * MIB,
        GIB,
        16 * GIB,
        MAX_STREAM_SIZE - 96,
    ] {
        let mut stream = GeneratedStream::at_offset(&seed(1), MAX_STREAM_SIZE, offset)?;
        ensure!(
            stream.generated_bytes() == 0,
            "seek to {offset} generated bytes"
        );
        ensure!(stream.cipher_position()? == offset);
        let mut out = [0u8; 96];
        ensure!(stream.read(&mut out)? == 96);
        ensure!(
            stream.generated_bytes() == 96,
            "offset {offset} changed the work done"
        );
        ensure!(stream.max_read_len() == 96);
    }
    Ok(())
}

#[test]
fn unit_gen_seek_matches_streaming_from_zero() -> Result<()> {
    let size = 100_000u64;
    let whole = read_all(&seed(1), size, 4096)?;
    for offset in [
        0u64, 1, 31, 63, 64, 65, 127, 128, 129, 4095, 4096, 4097, 99_999, 100_000,
    ] {
        let mut stream = GeneratedStream::new(&seed(1), size)?;
        stream.seek(offset)?;
        let mut out = vec![0u8; (size - offset) as usize];
        ensure!(stream.read(&mut out)? == out.len());
        ensure!(out == whole[offset as usize..], "offset {offset}");
    }
    Ok(())
}

#[test]
fn unit_gen_seek_backward_forward_repeated_and_current() -> Result<()> {
    let size = 10_000u64;
    let whole = read_all(&seed(2), size, 4096)?;
    let mut stream = GeneratedStream::new(&seed(2), size)?;
    let grab = |stream: &mut GeneratedStream, offset: u64, length: usize| -> Result<Vec<u8>> {
        stream.seek(offset)?;
        let mut out = vec![0u8; length];
        let n = stream.read(&mut out)?;
        out.truncate(n);
        Ok(out)
    };
    ensure!(grab(&mut stream, 5000, 100)? == whole[5000..5100]);
    ensure!(grab(&mut stream, 10, 100)? == whole[10..110]);
    ensure!(grab(&mut stream, 9000, 1000)? == whole[9000..10_000]);
    ensure!(grab(&mut stream, 0, 64)? == whole[..64]);
    stream.seek(stream.position())?;
    ensure!(stream.position() == 64);
    ensure!(grab(&mut stream, 5000, 100)? == whole[5000..5100]);
    ensure!(grab(&mut stream, 5000, 100)? == whole[5000..5100]);
    Ok(())
}

#[test]
fn unit_gen_eof_semantics() -> Result<()> {
    let mut stream = GeneratedStream::new(&seed(1), 200)?;
    stream.seek(200)?;
    let mut buf = [0u8; 64];
    ensure!(stream.read(&mut buf)? == 0);
    ensure!(stream.generated_bytes() == 0);
    ensure!(
        stream.seek(201)
            == Err(GenError::SeekPastEnd {
                offset: 201,
                size: 200
            })
    );
    ensure!(
        stream.position() == 200,
        "a rejected seek must not move the stream"
    );
    stream.seek(190)?;
    ensure!(stream.read(&mut buf)? == 10);
    ensure!(stream.read(&mut buf)? == 0);
    ensure!(stream.read(&mut [])? == 0);
    Ok(())
}

#[test]
fn unit_gen_chunk_independence() -> Result<()> {
    for size in [0u64, 1, 63, 64, 65, 127, 128, 129, 4095, 4096, 4097] {
        let reference = read_all(&seed(1), size, STREAM_CHUNK_SIZE)?;
        ensure!(reference.len() as u64 == size);
        for chunk in [1usize, 7, 63, 64, 65, 4096, STREAM_CHUNK_SIZE] {
            ensure!(
                read_all(&seed(1), size, chunk)? == reference,
                "size {size} chunk {chunk}"
            );
        }
    }
    Ok(())
}

#[test]
fn unit_gen_irregular_chunking() -> Result<()> {
    let size = MIB + 37;
    let reference = read_all(&seed(2), size, STREAM_CHUNK_SIZE)?;
    let mut state = 0x5eed_u32;
    let mut stream = GeneratedStream::new(&seed(2), size)?;
    let mut out = Vec::new();
    while (out.len() as u64) < size {
        state ^= state << 13;
        state ^= state >> 17;
        state ^= state << 5;
        let mut buf = vec![0u8; 1 + (state % 5000) as usize];
        let n = stream.read(&mut buf)?;
        out.extend_from_slice(&buf[..n]);
    }
    ensure!(out == reference);
    Ok(())
}

#[test]
fn unit_gen_identity_seed_and_size() -> Result<()> {
    let a = read_all(&seed(1), 4097, 1000)?;
    ensure!(
        read_all(&seed(1), 4097, 777)? == a,
        "same (seed, size) must reproduce"
    );
    ensure!(
        read_all(&seed(2), 4097, 1000)? != a,
        "different seeds must differ"
    );
    ensure!(
        read_all(&seed(1), 5000, 1000)?[..4097] == a[..],
        "a longer stream extends the shorter"
    );
    Ok(())
}

#[test]
fn unit_gen_zero_one_and_block_boundary_sizes() -> Result<()> {
    ensure!(read_all(&seed(1), 0, 64)?.is_empty());
    let reference = read_all(&seed(1), 130, 64)?;
    for size in [1usize, 63, 64, 65] {
        ensure!(read_all(&seed(1), size as u64, 64)? == reference[..size]);
    }
    Ok(())
}

#[test]
fn unit_gen_stream_capacity_boundary() -> Result<()> {
    ensure!(MAX_STREAM_SIZE == (1u64 << 38) - BLOCK_SIZE);
    GeneratedStream::new(&seed(1), MAX_STREAM_SIZE)?;
    for size in [MAX_STREAM_SIZE + 1, 1u64 << 38, 1u64 << 40, u64::MAX] {
        ensure!(
            matches!(
                GeneratedStream::new(&seed(1), size),
                Err(GenError::SizeExceedsCapacity { .. })
            ),
            "size {size}"
        );
    }

    let mut stream = GeneratedStream::new(&seed(1), MAX_STREAM_SIZE)?;
    stream.seek(MAX_STREAM_SIZE - 1)?;
    let mut buf = [0u8; 128];
    ensure!(stream.read(&mut buf)? == 1, "only the final byte remains");
    ensure!(stream.position() == MAX_STREAM_SIZE);
    ensure!(
        stream.read(&mut buf)? == 0,
        "nothing is generated beyond the cap"
    );
    ensure!(stream.seek(MAX_STREAM_SIZE + 1).is_err());
    Ok(())
}

#[test]
fn unit_gen_stream_tail_does_not_wrap_the_counter() -> Result<()> {
    let tail = generate_bytes(&seed(1), MAX_STREAM_SIZE, MAX_STREAM_SIZE - 128, 128)?;
    let head = generate_bytes(&seed(1), MAX_STREAM_SIZE, 0, 128)?;
    ensure!(
        tail != head,
        "counter wrap would replay the first keystream blocks"
    );
    Ok(())
}

#[test]
fn unit_gen_rejects_invalid_seeds_without_panicking() {
    let wide = "é".repeat(32);
    for bad in [
        "",
        "00",
        &"0".repeat(63),
        &"0".repeat(65),
        &"g".repeat(64),
        &format!("0x{}", "0".repeat(62)),
        &format!(" {}", "0".repeat(63)),
        wide.as_str(),
    ] {
        assert_eq!(Seed::from_hex(bad), Err(GenError::InvalidSeed), "{bad:?}");
        assert_eq!(
            Seed::from_canonical_hex(bad),
            Err(GenError::InvalidSeed),
            "{bad:?}"
        );
    }
    assert!(Seed::from_hex(&"A".repeat(64)).is_ok());
    assert_eq!(
        Seed::from_canonical_hex(&"A".repeat(64)),
        Err(GenError::InvalidSeed)
    );
}

#[test]
fn unit_gen_bounded_slice_allocation() {
    assert!(matches!(
        generate_bytes(&seed(1), MAX_STREAM_SIZE, 0, 512 * MIB),
        Err(GenError::SliceTooLarge { .. })
    ));
    assert!(matches!(
        generate_bytes(&seed(1), 100, 90, 20),
        Err(GenError::RangePastEnd { .. })
    ));
}
