export const PATHS = {
  root: "/",
  setup: "/setup",
  login: "/login",
  twoFactor: "/login/2fa",
  forcedPasswordChange: "/login/forced-password-change",
  enrollTwoFactor: "/login/enroll-2fa",
  resetPassword: "/reset-password/:token",
  invite: "/invite/:token",
  overview: "/overview",
  settings: "/settings",
  settingsProfile: "/settings/profile",
  settingsAppearance: "/settings/appearance",
  settingsSecurity: "/settings/security",
  settingsSessions: "/settings/sessions",
} as const;
