export const PATHS = {
  root: "/",
  setup: "/setup",
  login: "/login",
  twoFactor: "/login/2fa",
  forcedPasswordChange: "/login/forced-password-change",
  enrollTwoFactor: "/login/enroll-2fa",
  reauthComplete: "/auth/reauth-complete",
  resetPassword: "/reset-password/:token",
  invite: "/invite/:token",
  verifyEmail: "/verify-email/:token",
  verifyEmailMissing: "/verify-email",
  overview: "/overview",
  admin: "/admin",
  adminUsers: "/admin/users",
  adminUser: "/admin/users/:userId",
  adminSecurity: "/admin/security",
  adminSmtp: "/admin/smtp",
  adminProviders: "/admin/providers",
  settings: "/settings",
  settingsProfile: "/settings/profile",
  settingsAppearance: "/settings/appearance",
  settingsSecurity: "/settings/security",
  settingsSessions: "/settings/sessions",
} as const;
